[2024-11-22T14:49:17.041+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T14:49:17.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T14:49:17.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T14:49:17.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T14:49:17.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-21 00:00:00+00:00
[2024-11-22T14:49:17.104+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpihfxfikh']
[2024-11-22T14:49:17.110+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask fetch_data
[2024-11-22T14:49:17.111+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T14:49:17.112+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-11-22T14:49:17.169+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [running]> on host 53dfb9592961
[2024-11-22T14:49:17.264+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T14:49:17.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T14:49:17.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T14:49:17.290+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 25, in fetch_data_task
    from scripts.fetch_data import fetch_data
ModuleNotFoundError: No module named 'scripts.fetch_data'
[2024-11-22T14:49:17.300+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T144917, end_date=20241122T144917
[2024-11-22T14:49:17.312+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task fetch_data (No module named 'scripts.fetch_data'; 303)
[2024-11-22T14:49:17.326+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T14:49:17.348+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T14:49:17.351+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-22T15:51:26.643+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T15:51:26.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:51:26.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T15:51:26.681+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T15:51:26.693+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-21 00:00:00+00:00
[2024-11-22T15:51:26.719+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T15:51:26.709+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpq9n0bm9b']
[2024-11-22T15:51:26.720+0000] {standard_task_runner.py:63} INFO - Started process 294 to run task
[2024-11-22T15:51:26.720+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask fetch_data
[2024-11-22T15:51:26.765+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [running]> on host 53dfb9592961
[2024-11-22T15:51:26.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T15:51:26.846+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T15:51:26.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T15:51:26.866+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 25, in fetch_data_task
    from scripts.fetch_data import fetch_data
ModuleNotFoundError: No module named 'scripts.fetch_data'
[2024-11-22T15:51:26.877+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T155126, end_date=20241122T155126
[2024-11-22T15:51:26.888+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task fetch_data (No module named 'scripts.fetch_data'; 294)
[2024-11-22T15:51:26.896+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T15:51:26.915+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T15:51:26.918+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-22T16:15:33.309+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T16:15:33.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T16:15:33.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [queued]>
[2024-11-22T16:15:33.368+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T16:15:33.384+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-21 00:00:00+00:00
[2024-11-22T16:15:33.395+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'scheduled__2024-11-21T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmp2ca5llgz']
[2024-11-22T16:15:33.402+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask fetch_data
[2024-11-22T16:15:33.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=378) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T16:15:33.407+0000] {standard_task_runner.py:63} INFO - Started process 381 to run task
[2024-11-22T16:15:33.476+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-21T00:00:00+00:00 [running]> on host f85d7375f510
[2024-11-22T16:15:33.570+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-21T00:00:00+00:00'
[2024-11-22T16:15:33.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T16:15:35.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T16:15:35.321+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 27, in fetch_data_task
    from fetch_data import fetch_data
  File "/external_files/scripts/fetch_data.py", line 2, in <module>
    from vnstock import stock_historical_data
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/__init__.py", line 13, in <module>
    from .utils import *
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/utils.py", line 56, in <module>
    from IPython.display import display, Markdown, HTML
ModuleNotFoundError: No module named 'IPython'
[2024-11-22T16:15:35.333+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=scheduled__2024-11-21T00:00:00+00:00, execution_date=20241121T000000, start_date=20241122T161533, end_date=20241122T161535
[2024-11-22T16:15:35.348+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task fetch_data (No module named 'IPython'; 381)
[2024-11-22T16:15:35.387+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T16:15:35.409+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T16:15:35.411+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
