[2024-11-23T01:36:58.971+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:36:59.000+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:36:59.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:36:59.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-23T01:36:59.020+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-11-22 00:00:00+00:00
[2024-11-23T01:36:59.026+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'preprocess_data', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpwtwcj368']
[2024-11-23T01:36:59.029+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask preprocess_data
[2024-11-23T01:36:59.030+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:36:59.031+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2024-11-23T01:36:59.072+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [running]> on host ad983beda88b
[2024-11-23T01:36:59.142+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T01:36:59.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:37:00.107+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-23T01:37:00.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 34, in preprocess_data_task
    preprocess_data(stock_name, days)
  File "/external_files/scripts/preprocess_data.py", line 8, in preprocess_data
    data['Date'] = pd.to_datetime(data['date'], errors='coerce')
                                  ~~~~^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'date'
[2024-11-23T01:37:00.126+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=preprocess_data, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T013659, end_date=20241123T013700
[2024-11-23T01:37:00.138+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task preprocess_data ('date'; 170)
[2024-11-23T01:37:00.168+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-23T01:37:00.190+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:37:00.192+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-23T01:41:30.440+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:41:30.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:41:30.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:41:30.481+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-23T01:41:30.494+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-11-22 00:00:00+00:00
[2024-11-23T01:41:30.499+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'preprocess_data', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpycb5afaj']
[2024-11-23T01:41:30.502+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask preprocess_data
[2024-11-23T01:41:30.503+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=651) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:41:30.503+0000] {standard_task_runner.py:63} INFO - Started process 652 to run task
[2024-11-23T01:41:30.544+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.preprocess_data scheduled__2024-11-22T00:00:00+00:00 [running]> on host ad983beda88b
[2024-11-23T01:41:30.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T01:41:30.623+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:41:31.733+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-23T01:41:31.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-23T01:41:31.746+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=stock_price_prediction, task_id=preprocess_data, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T014130, end_date=20241123T014131
[2024-11-23T01:41:31.801+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-23T01:41:31.833+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:41:31.836+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
