[2024-11-22T14:50:29.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T14:50:29.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [queued]>
[2024-11-22T14:50:29.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [queued]>
[2024-11-22T14:50:29.681+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-11-22T14:50:29.699+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22 14:49:16.189039+00:00
[2024-11-22T14:50:29.707+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'manual__2024-11-22T14:49:16.189039+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmp8mceutxt']
[2024-11-22T14:50:29.710+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask fetch_data
[2024-11-22T14:50:29.712+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T14:50:29.713+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2024-11-22T14:50:29.764+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [running]> on host 53dfb9592961
[2024-11-22T14:50:29.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T14:49:16.189039+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T14:49:16.189039+00:00'
[2024-11-22T14:50:29.847+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T14:50:29.863+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T14:50:29.864+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 25, in fetch_data_task
    from scripts.fetch_data import fetch_data
ModuleNotFoundError: No module named 'scripts.fetch_data'
[2024-11-22T14:50:29.876+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=manual__2024-11-22T14:49:16.189039+00:00, execution_date=20241122T144916, start_date=20241122T145029, end_date=20241122T145029
[2024-11-22T14:50:29.886+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task fetch_data (No module named 'scripts.fetch_data'; 329)
[2024-11-22T14:50:29.927+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T14:50:29.949+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T14:50:29.951+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
