[2024-11-23T01:56:52.803+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:56:53.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.train_model_ANV manual__2024-11-23T01:52:07.286051+00:00 [queued]>
[2024-11-23T01:56:53.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.train_model_ANV manual__2024-11-23T01:52:07.286051+00:00 [queued]>
[2024-11-23T01:56:53.372+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-23T01:56:53.402+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model_ANV> on 2024-11-23 01:52:07.286051+00:00
[2024-11-23T01:56:53.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5134) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:56:53.421+0000] {standard_task_runner.py:63} INFO - Started process 5140 to run task
[2024-11-23T01:56:53.432+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'train_model_ANV', 'manual__2024-11-23T01:52:07.286051+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmplfc5g8zp']
[2024-11-23T01:56:53.453+0000] {standard_task_runner.py:91} INFO - Job 552: Subtask train_model_ANV
[2024-11-23T01:56:53.587+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.train_model_ANV manual__2024-11-23T01:52:07.286051+00:00 [running]> on host ad983beda88b
[2024-11-23T01:56:53.775+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='train_model_ANV' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T01:52:07.286051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T01:52:07.286051+00:00'
[2024-11-23T01:56:53.777+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:57:25.879+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107 UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
[2024-11-23T01:57:26.209+0000] {logging_mixin.py:188} INFO - Epoch 1/20
[2024-11-23T01:57:32.542+0000] {logging_mixin.py:188} INFO -  1/77 ━━━━━━━━━━━━━━━━━━━━ 7:57 6s/step - loss: 0.1127
[2024-11-23T01:57:32.584+0000] {logging_mixin.py:188} INFO -  2/77 ━━━━━━━━━━━━━━━━━━━━ 6s 84ms/step - loss: 0.1001
[2024-11-23T01:57:32.669+0000] {logging_mixin.py:188} INFO -  3/77 ━━━━━━━━━━━━━━━━━━━━ 6s 85ms/step - loss: 0.0892
[2024-11-23T01:57:32.741+0000] {logging_mixin.py:188} INFO -  5/77 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - loss: 0.0733
[2024-11-23T01:57:32.841+0000] {logging_mixin.py:188} INFO -  7/77 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0629
[2024-11-23T01:57:32.915+0000] {logging_mixin.py:188} INFO -  9/77 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.0556
[2024-11-23T01:57:33.052+0000] {logging_mixin.py:188} INFO - 11/77 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0500
[2024-11-23T01:57:33.136+0000] {logging_mixin.py:188} INFO - 13/77 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.0457
[2024-11-23T01:57:33.187+0000] {logging_mixin.py:188} INFO - 14/77 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.0438
[2024-11-23T01:57:33.258+0000] {logging_mixin.py:188} INFO - 15/77 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.0421
[2024-11-23T01:57:33.300+0000] {logging_mixin.py:188} INFO - 16/77 ━━━━━━━━━━━━━━━━━━━━ 3s 53ms/step - loss: 0.0406
[2024-11-23T01:57:33.376+0000] {logging_mixin.py:188} INFO - 18/77 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.0379
[2024-11-23T01:57:33.469+0000] {logging_mixin.py:188} INFO - 20/77 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.0356
[2024-11-23T01:57:33.564+0000] {logging_mixin.py:188} INFO - 22/77 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.0336
[2024-11-23T01:57:33.681+0000] {logging_mixin.py:188} INFO - 24/77 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.0319
[2024-11-23T01:57:33.757+0000] {logging_mixin.py:188} INFO - 25/77 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.0311
[2024-11-23T01:57:33.940+0000] {logging_mixin.py:188} INFO - 27/77 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0297
[2024-11-23T01:57:34.486+0000] {logging_mixin.py:188} INFO - 29/77 ━━━━━━━━━━━━━━━━━━━━ 3s 63ms/step - loss: 0.0284
[2024-11-23T01:57:35.056+0000] {logging_mixin.py:188} INFO - 30/77 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 0.0278
[2024-11-23T01:57:41.826+0000] {logging_mixin.py:188} INFO - 31/77 ━━━━━━━━━━━━━━━━━━━━ 5s 116ms/step - loss: 0.0272
[2024-11-23T01:57:41.866+0000] {logging_mixin.py:188} INFO - 32/77 ━━━━━━━━━━━━━━━━━━━━ 13s 302ms/step - loss: 0.0267
[2024-11-23T01:57:42.020+0000] {logging_mixin.py:188} INFO - 33/77 ━━━━━━━━━━━━━━━━━━━━ 13s 298ms/step - loss: 0.0261
[2024-11-23T01:57:42.088+0000] {logging_mixin.py:188} INFO - 34/77 ━━━━━━━━━━━━━━━━━━━━ 12s 291ms/step - loss: 0.0256
[2024-11-23T01:57:42.149+0000] {logging_mixin.py:188} INFO - 36/77 ━━━━━━━━━━━━━━━━━━━━ 11s 276ms/step - loss: 0.0247
[2024-11-23T01:57:42.301+0000] {logging_mixin.py:188} INFO - 38/77 ━━━━━━━━━━━━━━━━━━━━ 10s 265ms/step - loss: 0.0239
[2024-11-23T01:57:42.401+0000] {logging_mixin.py:188} INFO - 39/77 ━━━━━━━━━━━━━━━━━━━━ 9s 261ms/step - loss: 0.0235 
[2024-11-23T01:57:42.457+0000] {logging_mixin.py:188} INFO - 40/77 ━━━━━━━━━━━━━━━━━━━━ 9s 255ms/step - loss: 0.0231
[2024-11-23T01:57:42.534+0000] {logging_mixin.py:188} INFO - 41/77 ━━━━━━━━━━━━━━━━━━━━ 9s 251ms/step - loss: 0.0227
[2024-11-23T01:57:42.597+0000] {logging_mixin.py:188} INFO - 42/77 ━━━━━━━━━━━━━━━━━━━━ 8s 246ms/step - loss: 0.0224
[2024-11-23T01:57:42.729+0000] {logging_mixin.py:188} INFO - 43/77 ━━━━━━━━━━━━━━━━━━━━ 8s 244ms/step - loss: 0.0220
[2024-11-23T01:57:42.806+0000] {logging_mixin.py:188} INFO - 44/77 ━━━━━━━━━━━━━━━━━━━━ 7s 240ms/step - loss: 0.0217
[2024-11-23T01:57:42.918+0000] {logging_mixin.py:188} INFO - 46/77 ━━━━━━━━━━━━━━━━━━━━ 7s 232ms/step - loss: 0.0211
[2024-11-23T01:57:44.857+0000] {logging_mixin.py:188} INFO - 47/77 ━━━━━━━━━━━━━━━━━━━━ 7s 237ms/step - loss: 0.0208
[2024-11-23T01:58:34.062+0000] {logging_mixin.py:188} INFO - 48/77 ━━━━━━━━━━━━━━━━━━━━ 9s 333ms/step - loss: 0.0205
[2024-11-23T01:59:08.767+0000] {logging_mixin.py:188} INFO - 49/77 ━━━━━━━━━━━━━━━━━━━━ 56s 2s/step - loss: 0.0202  
[2024-11-23T01:59:08.966+0000] {logging_mixin.py:188} INFO - 50/77 ━━━━━━━━━━━━━━━━━━━━ 53s 2s/step - loss: 0.0200
[2024-11-23T01:58:33.772+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-23T01:59:09.258+0000] {logging_mixin.py:188} INFO - 52/77 ━━━━━━━━━━━━━━━━━━━━ 47s 2s/step - loss: 0.0194
[2024-11-23T01:59:09.057+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-23T01:59:09.386+0000] {logging_mixin.py:188} INFO - 53/77 ━━━━━━━━━━━━━━━━━━━━ 44s 2s/step - loss: 0.0192
[2024-11-23T01:59:10.061+0000] {logging_mixin.py:188} INFO - 54/77 ━━━━━━━━━━━━━━━━━━━━ 42s 2s/step - loss: 0.0190
[2024-11-23T01:59:10.132+0000] {logging_mixin.py:188} INFO - 56/77 ━━━━━━━━━━━━━━━━━━━━ 37s 2s/step - loss: 0.0185
[2024-11-23T01:59:10.350+0000] {logging_mixin.py:188} INFO - 57/77 ━━━━━━━━━━━━━━━━━━━━ 34s 2s/step - loss: 0.0183
[2024-11-23T01:59:10.491+0000] {logging_mixin.py:188} INFO - 58/77 ━━━━━━━━━━━━━━━━━━━━ 32s 2s/step - loss: 0.0181
[2024-11-23T01:59:10.641+0000] {logging_mixin.py:188} INFO - 59/77 ━━━━━━━━━━━━━━━━━━━━ 30s 2s/step - loss: 0.0179
[2024-11-23T01:59:10.986+0000] {logging_mixin.py:188} INFO - 61/77 ━━━━━━━━━━━━━━━━━━━━ 26s 2s/step - loss: 0.0175
[2024-11-23T01:59:11.149+0000] {logging_mixin.py:188} INFO - 62/77 ━━━━━━━━━━━━━━━━━━━━ 24s 2s/step - loss: 0.0173
[2024-11-23T01:59:11.234+0000] {logging_mixin.py:188} INFO - 64/77 ━━━━━━━━━━━━━━━━━━━━ 20s 2s/step - loss: 0.0169
[2024-11-23T01:59:11.305+0000] {logging_mixin.py:188} INFO - 66/77 ━━━━━━━━━━━━━━━━━━━━ 16s 2s/step - loss: 0.0166
[2024-11-23T01:59:11.739+0000] {logging_mixin.py:188} INFO - 68/77 ━━━━━━━━━━━━━━━━━━━━ 13s 1s/step - loss: 0.0162
[2024-11-23T01:59:12.679+0000] {logging_mixin.py:188} INFO - 69/77 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step - loss: 0.0161
[2024-11-23T01:59:12.706+0000] {logging_mixin.py:188} INFO - 70/77 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - loss: 0.0159
[2024-11-23T01:59:12.764+0000] {logging_mixin.py:188} INFO - 71/77 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - loss: 0.0158 
[2024-11-23T01:59:12.990+0000] {logging_mixin.py:188} INFO - 73/77 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - loss: 0.0155
[2024-11-23T01:59:13.453+0000] {logging_mixin.py:188} INFO - 74/77 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - loss: 0.0153
[2024-11-23T01:59:14.205+0000] {logging_mixin.py:188} INFO - 75/77 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step - loss: 0.0152
[2024-11-23T01:59:15.182+0000] {logging_mixin.py:188} INFO - 76/77 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.0151
[2024-11-23T01:59:16.860+0000] {logging_mixin.py:188} INFO - 77/77 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - loss: 0.0149
[2024-11-23T02:00:49.343+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-23T02:01:19.468+0000] {logging_mixin.py:188} INFO - 77/77 ━━━━━━━━━━━━━━━━━━━━ 233s 3s/step - loss: 0.0148
[2024-11-23T02:01:19.474+0000] {logging_mixin.py:188} INFO - Epoch 2/20
[2024-11-23T02:01:19.615+0000] {logging_mixin.py:188} INFO -  1/77 ━━━━━━━━━━━━━━━━━━━━ 10s 133ms/step - loss: 0.0021
[2024-11-23T02:01:19.692+0000] {logging_mixin.py:188} INFO -  3/77 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.0016  
[2024-11-23T02:01:19.761+0000] {logging_mixin.py:188} INFO -  5/77 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - loss: 0.0017
